name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run npm install
        run: yarn
      - name: creates output
        run:  yarn build
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'build'
          destination-github-username: 'saitejach127'
          destination-repository-name: 'ig_build'
          user-email: saitejach127@gmail.com
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to ec2
        uses: appleboy/ssh-action@master
        with: 
          host: ec2-34-237-4-72.compute-1.amazonaws.com
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            sudo su
            cd /var/www/html
            ls